config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :comments
  resources :artworks
  resources :users
  resources :sessions
  resources :searches
  root 'application#index'
  post '/comments/:id', to: 'comments#destroy'
  get '/login', to: 'sessions#new', as: 'login'
  post '/logout', to: 'sessions#destroy', as: 'logout'
  post '/sessions', to: 'sessions#create', as: 'create_session'
  post '/like/:id', to: 'votes#like', as: 'like'
  post '/dislike', to: 'votes#dislike', as: 'dislike'
  post '/destroy', to: 'comments#destroy', as: 'destroy_comment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  has_many :artwork_tags
  has_many :tags, through: :artwork_tags
  has_many :votes
  has_many :comments
  belongs_to :user

  mount_uploader :image, ImageUploader

  validates :name, presence: :true
  validates :image, presence: :true
  validates_processing_of :image
  validate :image_size_validation

  before_save :make_title

  def make_title
    if !self.name.present?
      self.name = "Untitled"
    end
  end

  def self.search(search)
    if search
      where(["name LIKE ?", "%#{search}%"])
    else
      all
    end
  end

  def year
    if self.tags.all.present?
      self.tags.all.find{|t| t.category == "year"}
    end
  end

  def style
    if self.tags.all.present?
      self.tags.all.select{|t| t.category == "style"}
    else
      []
    end
  end

  def medium
    if self.tags.all.present?
      self.tags.all.select{|t| t.category == "medium"}
    else
      []
    end
  end

  def c_style
    if self.tags.all.present?
      self.tags.all.select{|t| t.category == "custom style"}
    else
      []
    end
  end

  def c_medium
    if self.tags.all.present?
      self.tags.all.select{|t| t.category == "custom medium"}
    else
      []
    end
  end

  def c_tag
    if self.tags.all.present?
      self.tags.all.select{|t| t.category == "custom tag"}
    else
          []
    end
  end

  def artist_name
    self.artist.name
  end

  private
    def image_size_validation
      errors[:image] << "should be less than 600KB" if image.size > 0.6.megabytes
    end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController

  before_action :get_artwork, only: [:show]
  def index
    @artworks = Artwork.search(params[:search])
    if params[:search]
      @search = true
    end
  end

  def show
    @comments = Comment.all.where(artwork_id: params[:id])
    @comment = Comment.new
    @votes = Vote.all.where(artwork_id: params[:id])
    @vote_num = @votes.map{|vote| vote.value }.sum
  end

  def new
    @artwork = Artwork.new
    @styles = Tag.where(category: "style")
    @media = Tag.where(category: "medium")
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.user_id = session[:user_id]
    if @artwork.save
      @year_tag = Tag.find_or_create_by(category: "year", name: params[:artwork][:year])
      ArtworkTag.create(artwork_id: @artwork.id, tag_id: @year_tag.id)
      params[:artwork][:tag_ids].reject { |c| c.empty? }.each {|id| ArtworkTag.create(artwork_id: @artwork.id, tag_id: id.to_i) } if params[:artwork][:tag_ids]
      @style_tag = Tag.find_or_create_by(category: "custom style", name: params[:artwork][:style]) ##this allows user to create new custom tag where style tag already exists
      ArtworkTag.create(artwork_id: @artwork.id, tag_id: @style_tag.id)
      @medium_tag = Tag.find_by( name: params[:artwork][:medium]) ## but this might find a custom tag of the wrong category
      if !@medium_tag
        @medium_tag = Tag.create(category: "custom medium", name: params[:artwork][:medium])
      end
      ArtworkTag.create(artwork_id: @artwork.id, tag_id: @medium_tag.id)
      params[:mytext].reject { |c| c.empty? }.each {|tag_name| ArtworkTag.find_or_create_by(artwork_id: @artwork.id, tag_id: Tag.find_or_create_by(category: "custom tag", name: tag_name).id) }
      redirect_to @artwork
    else
      render :new
    end
  end

  private

    def get_artwork
      @artwork = Artwork.find(params[:id])
    end

    def artwork_params
      params.require(:artwork).permit(:name, :user_id, :image).merge(user_id: current_user.id)
    end


end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/index.erb
<!-- hides the background images from showing -->

<% if @search %>
<h1 style="font-family: 'Quicksand', sans-serif;">Search Results</h1><hr><br>
<% else %>
<h1 style="font-family: 'Quicksand', sans-serif;">All Artworks</h1><hr><br>
<% end %>
<div class="ui very relaxed grid container">
  <% @artworks.each do |artwork|%>
  <div class="four wide column">
    <div class="row">
      <div class="column middle aligned">
        <div class="ui fluid image"><%= link_to image_tag(artwork.image.url), artwork_path(artwork) %>
        </div>
      </div><br>
      <div class="column">
        <strong><%= artwork.name %></strong><br>
      </div>
      <div class="column">
        <%= artwork.user.name %><br>
      </div>
      <div class="column">
        <i><%= artwork.year.name %></i>
      </div>
      <br>
    </div>
  </div>
  <%end%>
</div>

app/views/artworks/new.erb
<style type="text/css">
 body {
     background-image: none;
 }
</style>
<% if @artwork.errors.any? %>
<div class="ui error message">
  <div class="header">
    <h4>
      <!-- <%= pluralize(@artwork.errors.count, "error") %>
      prohibited this artwork from being created: -->
      Something went wrong...
    </h4>
  </div>
  <ul class="list">
    <% @artwork.errors.full_messages.each do |message| %>
    <li><%=message%></li>
    <% end %>
  </ul>
</div>
<% end %>
<% if @artwork.errors.any? %>
<div id="form_shake">
<%else%>
<div id="form_padding" style="opacity:0.8">
<%end%>

<div id="artwork_new_padding">
  <div class="ui form">
    <%= form_for @artwork, html: { multipart: true } do |f| %>


    <h4 class="ui dividing header">Upload an Original Artwork</h4>

    <div class="field">
      <label>Name</label>
        <div class="field">
          <%= f.text_field :name %>
        </div>
    </div>

    <div class="field">
      <label>Year Created</label>
        <div class="field">
          <%= f.text_field :year %>
        </div>
    </div>

    <div class="field">
      <label>Upload Image</label>
        <div class="field">
          <%= f.file_field :image %>
        </div>
    </div>

    <!-- <div class="inline fields"> -->
    <div class="inline fields ">
      <label for="style">Select a Style for your masterpiece:</label> <br>

      <%= f.collection_check_boxes :tag_ids, @styles, :id, :name %>

      <br><br>
      <p>Other Styles: <%= f.text_field :style %></p>
      </div>
    <!-- </div> -->


    <div class="inline fields">
      <label for="style">Select a Medium for your masterpiece:</label><br>

      <%= f.collection_check_boxes :tag_ids, @media, :id, :name %>

      <br><br>
      <p>Other Media: <%= f.text_field :medium %></p>
    </div>

    <div class="input_fields_wrap">
      <button class="ui basic small button">Add Tags!!</button><br><br>
      <input type="text" name="mytext[]", placeholder="Add additional tags to your image"><br><br>
    </div>

    <div class="actions">
      <br><%= f.submit %></br>
    </div>
    <%end%>
  </div>
</div>

app/views/artworks/show.erb
<div style="font-size: 130%">
  <strong><%= @artwork.name %></strong>  <br>
  <%= link_to @artwork.user.name, @artwork.user %> <br>
  <i><%= @artwork.year ? @artwork.year.name : "year unknown" %></i><br><br>
</div>

<% if (@artwork.style+@artwork.c_style).empty? %>
<% elsif (@artwork.style+@artwork.c_style).count == 1 %>
  <strong>Style:</strong>
<% else %>
  <strong>Styles:</strong>
<% end %>
<%= (@artwork.style+@artwork.c_style).reject { |tag| tag.name.empty? }.map { |style|  link_to style.name.capitalize, style }.join(", ").html_safe if !!(@artwork.style+@artwork.c_style)%>
<br>

<% if (@artwork.medium+@artwork.c_medium).empty? %>
<% elsif (@artwork.medium+@artwork.c_medium).count == 1 %>
  <strong>Medium:</strong>
<% else  %>
  <strong>Media:</strong>
<% end %>
<%= (@artwork.medium+@artwork.c_medium).reject { |tag| tag.name.empty? }.map { |medium| link_to medium.name.capitalize, medium}.join(", ").html_safe if !!(@artwork.medium+@artwork.c_medium)%>
<br>

<% if !@artwork.c_tag.empty? %>
Tags:
<%= @artwork.c_tag.reject { |tag| tag.name.empty? }.map {|tag| link_to tag.name.capitalize, tag}.join(", ").html_safe %><br><br>
<% end %>
<br> <hr><br><br>

<div class="ui grid">

    <div class="five wide column">
      <div class="ui large image">
        <%= image_tag @artwork.image.url %>
      </div>
      <br><br>


      <div class="ui icon input">
        <%= form_tag like_path do %>
          <input name="artwork_id" type="hidden" value="<%= @artwork.id %>" />
          <button class="ui icon basic button">
            <i class="thumbs up outline icon"></i>
          </button>
        <% end %>
      </div>

      <div class="ui icon input">
        <%= form_tag dislike_path do %>
          <input name="artwork_id" type="hidden" value="<%= @artwork.id %>" />
          <button class="ui icon basic button">
            <i class="thumbs down outline icon"></i>
          </button>
        <% end %>
      </div>

      <br><br>
      <div>
        Likes: <%= @vote_num %>
      </div>

    </div>

    <div class="six wide column">
      <div class="ui reply form">
        <%= form_for @comment do |f|%>
          <%= f.hidden_field :artwork_id, value: @artwork.id %>
          <%= f.hidden_field :user_id, value: session[:user_id] %>
          <%= f.label :comment %><br>
          <div class="field">
            <%= f.text_area :content %><br>
          </div>

            <%= f.submit class: "ui basic button"%>

        <% end %>
      </div><br><br>
      <div class="container">
        <% if @comments %>
          <% @comments.each do |comment| %>
            <strong><%= comment.user.name %></strong> <br>
            <%= comment.content %><br><br>
              <% if comment.user_id == session[:user_id] %>
              <div style="float:left;">
              <%= button_to "Delete Comment", {controller: :comments, method: :post, action: :destroy, comment_id: comment.id}, {class: "ui basic small button"}%>
            </div>
            <div style="float:left;">
            <%= link_to "Edit Comment", "#", :id => 'showCommentEdit', class: "ui basic small button" %><br><br>
          </div><br>
            <div class="ui reply form">
              <div id="editComment">
                <%= form_for comment do |f|%>
                  <%= f.hidden_field :artwork_id, value: @artwork.id %>
                  <%= f.hidden_field :user_id, value: session[:user_id] %><br><br>
                  <br><%= f.label :comment %></br>
                  <%= f.text_area :content %><br>
                  <%= button_to "Update Comment", {controller: :comments, method: :get, action: :update, comment_id: comment.id}, {class: "ui basic small button"} %><br><br>
                <% end %>
              </div>
            </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>