config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :comments
  resources :artworks
  resources :users
  resources :sessions
  resources :searches
  root 'application#index'
  post '/comments/:id', to: 'comments#destroy'
  get '/login', to: 'sessions#new', as: 'login'
  post '/logout', to: 'sessions#destroy', as: 'logout'
  post '/sessions', to: 'sessions#create', as: 'create_session'
  post '/like/:id', to: 'votes#like', as: 'like'
  post '/dislike', to: 'votes#dislike', as: 'dislike'
  post '/destroy', to: 'comments#destroy', as: 'destroy_comment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Art Critic</title>
<%= favicon_link_tag asset_path('logo.png'), :rel => 'icon', :type =>  'image/png' %>
  <!-- Important! Links to JS and stylesheets -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <style>
      body {
        font-family: 'Quicksand', sans-serif;
        background: #f9f9f9
      }
      h1 {
        font-family: 'Quicksand', sans-serif;
        color: #006aff;
      }
      h2 {
        font-family: 'Quicksand', sans-serif;
        color: #006aff;
      }
    </style>

</head>
<body style="padding: 5em;">



<% if !session[:user_id] %>
  <div class="ui large top fixed hidden menu">
    <div class="ui container">
      <div class="left menu">

        <div class="item">
          <div class="ui image mini">
              <%= image_tag 'logo.png' %>
          </div>
        </div>
        <div class="item">
          <a class="" href="/artworks" style="font-family: 'Quicksand', sans-serif;">All Artworks</a>
        </div>
        <div class="item">
          <a class="" href="/users" style="font-family: 'Quicksand', sans-serif;">All Artists</a>
        </div>
        <div class="item">
          <div class="ui icon input">
            <%= form_tag artworks_path, method: "get" do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search by artwork name" %>
              <button class="ui icon basic button">
                <i class="search icon"></i>
              </button>
            <% end %>
          </div>
        </div>
        <div class="item">
          <a class="" href="<%=new_search_path %>" style="font-family: 'Quicksand', sans-serif;">Advanced Search</a>
        </div>
      </div>

      <div class="right menu">
        <div class="item">
          <a class="" href="/login" style="font-family: 'Quicksand', sans-serif;">Sign In</a>
        </div>
        <div class="item">
          <a class="" href="/users/new" style="font-family: 'Quicksand', sans-serif;">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
<% else %>

  <div class="ui large top fixed hidden menu">
    <div class="ui container">
      <div class="right menu">
        <div class="item">
          <%= link_to "Sign Out", logout_path, method: "post"%>
        </div>
      </div>
      <div class="left menu">

        <div class="item">
          <div class="ui image mini">
              <%= image_tag 'logo.png' %>
          </div>
        </div>
        <div class="item">
          <a class="" href="/users/<%=session[:user_id]%>" style="font-family: 'Quicksand', sans-serif;">Home</a>
        </div>
        <div class="item">
          <a class="" href="/artworks" style="font-family: 'Quicksand', sans-serif;">All Artworks</a>
        </div>
        <div class="item">
          <a class="" href="/users" style="font-family: 'Quicksand', sans-serif;">All Artists</a>
        </div>
        <div class="item">
          <a class="" href="/artworks/new" style="font-family: 'Quicksand', sans-serif;">Add Artwork</a>
        </div>
        <div class="item">
          <div class="ui icon input">
            <%= form_tag artworks_path, method: "get" do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search by artwork name" %>
              <button class="ui icon basic button">
                <i class="search icon"></i>
              </button>
            <% end %>
          </div>
        </div>
        <div class="item">
          <a class="" href="<%=new_search_path %>" style="font-family: 'Quicksand', sans-serif;">Advanced Search</a>
        </div>
      </div>
    </div>
  </div>
<% end %>
  <%= yield %>
</body>
</html>